packages:
  - packages/bluesky/*
  - packages/clients/*
  - packages/definitions/*
  - packages/identity/*
  - packages/internal/*
  - packages/lexicons/*
  - packages/misc/*
  - packages/oauth/*
  - packages/servers/*
  - packages/utilities/*

allowBuilds:
  better-sqlite3: true
  cbor-extract: true
  core-js: false
  esbuild: true
  protobufjs: false
  sharp: true

minimumReleaseAgeExclude:
  - '@mary-ext/*'
  - '@oomfware/*'

patchedDependencies:
  '@atproto/pds@0.5.29': patches/@atproto__pds@0.5.29.patch
