packages:
  - packages/bluesky/*
  - packages/clients/*
  - packages/definitions/*
  - packages/identity/*
  - packages/internal/*
  - packages/lexicons/*
  - packages/misc/*
  - packages/oauth/*
  - packages/servers/*
  - packages/utilities/*

allowBuilds:
  esbuild: set this to true or false

onlyBuiltDependencies:
  - better-sqlite3
  - cbor-extract
  - esbuild
  - sharp
