// this file is generated by scripts/generate-limits.js
// do not edit manually

/** limits for `app.bsky.actor.profile` */
export const actorProfile = {
	avatar: { maxSize: 1_000_000 },
	banner: { maxSize: 1_000_000 },
	pronouns: { maxGraphemes: 20, maxLength: 200 },
	description: { maxGraphemes: 256, maxLength: 2_560 },
	displayName: { maxGraphemes: 64, maxLength: 640 },
} as const;

/** limits for `app.bsky.feed.generator` */
export const feedGenerator = {
	avatar: { maxSize: 1_000_000 },
	description: { maxGraphemes: 300, maxLength: 3_000 },
	displayName: { maxGraphemes: 24, maxLength: 240 },
} as const;

/** limits for `app.bsky.feed.post` */
export const feedPost = {
	tags: {
		maxItems: 8,
		item: { maxGraphemes: 64, maxLength: 640 },
	},
	text: { maxGraphemes: 300, maxLength: 3_000 },
	langs: { maxItems: 3 },
} as const;

/** limits for `app.bsky.feed.postgate` */
export const feedPostgate = {
	embeddingRules: { maxItems: 5 },
	detachedEmbeddingUris: { maxItems: 50 },
} as const;

/** limits for `app.bsky.feed.threadgate` */
export const feedThreadgate = {
	allow: { maxItems: 5 },
	hiddenReplies: { maxItems: 300 },
} as const;

/** limits for `app.bsky.graph.list` */
export const graphList = {
	name: { maxLength: 64, minLength: 1 },
	avatar: { maxSize: 1_000_000 },
	description: { maxGraphemes: 300, maxLength: 3_000 },
} as const;

/** limits for `app.bsky.graph.starterpack` */
export const graphStarterpack = {
	name: { maxGraphemes: 50, maxLength: 500, minLength: 1 },
	feeds: { maxItems: 3 },
	description: { maxGraphemes: 300, maxLength: 3_000 },
} as const;

/** limits for `app.bsky.embed.external` */
export const embedExternal = {
	colorRGB: {
		b: { maximum: 255 },
		g: { maximum: 255 },
		r: { maximum: 255 },
	},
	external: {
		thumb: { maxSize: 1_000_000 },
	},
} as const;

/** limits for `app.bsky.embed.gallery` */
export const embedGallery = {
	items: { maxItems: 20 },
	image: {
		image: { maxSize: 2_000_000 },
	},
} as const;

/** limits for `app.bsky.embed.images` */
export const embedImages = {
	images: { maxItems: 4 },
	image: {
		image: { maxSize: 2_000_000 },
	},
} as const;

/** limits for `app.bsky.embed.video` */
export const embedVideo = {
	video: { maxSize: 300_000_000 },
	captions: { maxItems: 20 },
	caption: {
		file: { maxSize: 20_000 },
	},
} as const;

/** limits for `app.bsky.richtext.facet` */
export const richtextFacet = {
	tag: {
		tag: { maxGraphemes: 64, maxLength: 640 },
	},
} as const;

/** limits for `chat.bsky.convo.defs` */
export const convoMessage = {
	text: { maxGraphemes: 1_000, maxLength: 10_000 },
} as const;
